# Generated by Django 4.2.7 on 2024-01-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qNo', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('statement', models.TextField()),
                ('inputFormat', models.TextField()),
                ('outputFormat', models.TextField()),
                ('inputConstraint', models.TextField()),
                ('sampleData', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='DateModified',
            new_name='dateModified',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='IsArchived',
            new_name='isArchived',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='IsTrash',
            new_name='isTrash',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='OwnerId',
            new_name='ownerId',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjName',
            new_name='projName',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectContent',
            new_name='projectContent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.CreateModel(
            name='TableSubmission',
            fields=[
                ('submitId', models.AutoField(primary_key=True, serialize=False)),
                ('isSuccessful', models.BooleanField()),
                ('submitLang', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField()),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('qNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('rankId', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('level', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
