# Generated by Django 5.0.1 on 2024-01-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
                ("statement", models.TextField()),
                ("inputFormat", models.TextField()),
                ("outputFormat", models.TextField()),
                ("inputConstraint", models.TextField()),
            ],
        ),
    ]
