# Generated by Django 5.0.1 on 2024-01-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("advance", "Advance"),
                            ("intermediate", "Intermediate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("hard", "Hard"),
                            ("medium", "Medium"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("points", models.IntegerField()),
                ("statement", models.TextField()),
                ("inputFormat", models.TextField()),
                ("outputFormat", models.TextField()),
                ("sampleInput", models.TextField()),
                ("sampleOutput", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="tablesubmission",
            name="qNumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.challenge"
            ),
        ),
        migrations.DeleteModel(
            name="Challenges",
        ),
    ]
