# Generated by Django 4.2.7 on 2024-01-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_rename_datemodified_project_datemodified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sampleData',
        ),
    ]
