# Generated by Django 4.2.7 on 2024-01-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_question_sampledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sampleData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
